APP_CONTROL = "APP_CONTROL"
SYSTEM_INFO = "SYSTEM_INFO"
SCREEN_CAPTURE = "SCREEN_CAPTURE"
FILE_READ = "FILE_READ"
FILE_DELETE = "FILE_DELETE"
NETWORK_CONTROL = "NETWORK_CONTROL"

ALL_SCOPES = {
    APP_CONTROL,
    SYSTEM_INFO,
    SCREEN_CAPTURE,
    FILE_READ,
    FILE_DELETE,
    NETWORK_CONTROL,
}
